general:
  debug_level: INFO
  input_filelist_path: "../metadata/filelist.txt"
  input_sumweights_path: "../metadata/sum_of_weights.txt"
  output_path_histograms: "../output_histograms/"
  output_path_ntuples: "../output_ntuples/"
  default_sumweights: "NOSYS"
  default_event_weights: "weight_mc_NOSYS * weight_pileup_NOSYS * weight_leptonSF_tight_NOSYS * weight_jvt_effSF_NOSYS"
  default_reco_tree_name: "reco"
  xsection_files:
    - files: ["/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/dev/PMGTools/PMGxsecDB_mc23.txt"]
      campaigns: ["mc23a", "mc23e", "mc23d"]
  luminosity:
    mc23a: 29300.0
  #  mc23e: 109400.0
  #  mc23d: 26700.0
  automatic_systematics: False
  nominal_only: True
  config_define_after_custom_class : True
  create_tlorentz_vectors_for: ["jet", "el", "mu"]
  use_rvec: True
  number_of_cpus: 12
  use_region_subfolders: True
  custom_frame_name: "MyCustomFrame"


regions:
  # Regions for "as a function of the number of jets"
  - name: "raw_region"
    selection: "selection_cuts_NOSYS == 1 || selection_cuts_NOSYS == 0" # Raw selection
  - name: "sec_region"
    selection: "selection_cuts_NOSYS == 1"
  - name: "2jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "3jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 3"
  - name: "4jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 4"
  - name: "5jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 5"
  - name: "6jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 6"
  - name: "7jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 7"
  - name: "8jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 8"
  - name: "9jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 9"
  - name: "10jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS == 10"
  - name: "geq2jets_region"
    selection: "selection_cuts_NOSYS == 1 && jet_size_NOSYS >= 2"

  # Regions for "as a function of jet pT"
  - name: "jet_pt_region_0to30_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_0to30_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_30to60_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_30to60_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_60to90_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_60to90_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_90to120_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_90to120_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_120to150_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_120to150_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_150to180_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_150to180_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_180to210_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_180to210_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_210to240_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_210to240_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_240to270_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_240to270_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_270to300_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_270to300_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_300to330_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_300to330_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_330to360_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_330to360_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_360to390_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_360to390_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_390to420_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_390to420_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_420to450_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_420to450_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_450to480_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_450to480_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_480to510_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_480to510_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_510to540_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_510to540_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_540to570_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_540to570_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_570to600_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_570to600_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_600to630_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_600to630_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_630to660_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_630to660_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_660to690_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_660to690_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_690to720_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_690to720_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_720to750_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_720to750_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_750to780_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_750to780_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_780to810_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_780to810_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_810to840_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_810to840_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_840to870_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_840to870_GeV_NOSYS == 1 && jet_size_NOSYS == 2"
  - name: "jet_pt_region_870to900_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && jet_pt_region_870to900_GeV_NOSYS == 1 && jet_size_NOSYS == 2"


  # Regions for "as a function of SV Invariant Mass"
  - name: "sv_invariant_mass_region_0to0point5_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_0to0point5_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_0point5to1_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_0point5to1_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_1to1point5_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_1to1point5_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_1point5to2_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_1point5to2_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_2to2point5_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_2to2point5_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_2point5to3_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_2point5to3_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_3to3point5_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_3to3point5_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_3point5to4_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_3point5to4_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_4to4point5_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_4to4point5_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_4point5to5_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_4point5to5_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_5to5point5_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_5to5point5_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"
  - name: "sv_invariant_mass_region_5point5to6_GeV_region"
    selection: "selection_cuts_NOSYS == 1 && sv_invariant_mass_region_5point5to6_GeV_NOSYS == 1 && jet_size_NOSYS >= 2"

ntuples:
  regions:
    - raw_region
    - sec_region
    - 2jets_region
    - 3jets_region
    - 4jets_region
    - 5jets_region
    - 6jets_region
    - 7jets_region
    - 8jets_region
    - 9jets_region
    - 10jets_region 
    - geq2jets_region

    - jet_pt_region_0to30_GeV_region
    - jet_pt_region_30to60_GeV_region
    - jet_pt_region_60to90_GeV_region
    - jet_pt_region_90to120_GeV_region
    - jet_pt_region_120to150_GeV_region
    - jet_pt_region_150to180_GeV_region
    - jet_pt_region_180to210_GeV_region
    - jet_pt_region_210to240_GeV_region
    - jet_pt_region_240to270_GeV_region
    - jet_pt_region_270to300_GeV_region
    - jet_pt_region_300to330_GeV_region
    - jet_pt_region_330to360_GeV_region
    - jet_pt_region_360to390_GeV_region
    - jet_pt_region_390to420_GeV_region
    - jet_pt_region_420to450_GeV_region
    - jet_pt_region_450to480_GeV_region
    - jet_pt_region_480to510_GeV_region
    - jet_pt_region_510to540_GeV_region
    - jet_pt_region_540to570_GeV_region
    - jet_pt_region_570to600_GeV_region
    - jet_pt_region_600to630_GeV_region
    - jet_pt_region_630to660_GeV_region
    - jet_pt_region_660to690_GeV_region
    - jet_pt_region_690to720_GeV_region
    - jet_pt_region_720to750_GeV_region
    - jet_pt_region_750to780_GeV_region
    - jet_pt_region_780to810_GeV_region
    - jet_pt_region_810to840_GeV_region
    - jet_pt_region_840to870_GeV_region
    - jet_pt_region_870to900_GeV_region

    - sv_invariant_mass_region_0to0point5_GeV_region
    - sv_invariant_mass_region_0point5to1_GeV_region
    - sv_invariant_mass_region_1to1point5_GeV_region
    - sv_invariant_mass_region_1point5to2_GeV_region
    - sv_invariant_mass_region_2to2point5_GeV_region
    - sv_invariant_mass_region_2point5to3_GeV_region
    - sv_invariant_mass_region_3to3point5_GeV_region
    - sv_invariant_mass_region_3point5to4_GeV_region
    - sv_invariant_mass_region_4to4point5_GeV_region
    - sv_invariant_mass_region_4point5to5_GeV_region
    - sv_invariant_mass_region_5to5point5_GeV_region
    - sv_invariant_mass_region_5point5to6_GeV_region
  # If you want a selection here, use the same as the region:
  #selection: "selection_cuts_NOSYS" #&& jet_size_NOSYS == 2
  branches:
    - jet_size_NOSYS
    - selection_cuts_NOSYS
    - ordered_jet_truth_flavour_NOSYS 
    - raw_chi2_minval_truthall_NOSYS # For chi2 correct vs. mis-correct analysis
    - sv1_ordered_jets_NOSYS # For SV1 analysis
    - raw_chi2_pairing_NOSYS
    # additional truth distributions - for mean and std extraction
    - new_truth_mlpb_NOSYS
    - new_truth_mlmbb_NOSYS
    #- new_truth_pTdiff_NOSYS
    #- new_truth_sum_deltaR_NOSYS
    #- new_truth_mllbb_NOSYS
    #- new_truth_mT_ttbar_NOSYS

    - jet_pt_region_0to30_GeV_NOSYS
    - jet_pt_region_30to60_GeV_NOSYS
    - jet_pt_region_60to90_GeV_NOSYS
    - jet_pt_region_90to120_GeV_NOSYS
    - jet_pt_region_120to150_GeV_NOSYS
    - jet_pt_region_150to180_GeV_NOSYS
    - jet_pt_region_180to210_GeV_NOSYS
    - jet_pt_region_210to240_GeV_NOSYS
    - jet_pt_region_240to270_GeV_NOSYS
    - jet_pt_region_270to300_GeV_NOSYS
    - jet_pt_region_300to330_GeV_NOSYS
    - jet_pt_region_330to360_GeV_NOSYS
    - jet_pt_region_360to390_GeV_NOSYS
    - jet_pt_region_390to420_GeV_NOSYS
    - jet_pt_region_420to450_GeV_NOSYS
    - jet_pt_region_450to480_GeV_NOSYS
    - jet_pt_region_480to510_GeV_NOSYS
    - jet_pt_region_510to540_GeV_NOSYS
    - jet_pt_region_540to570_GeV_NOSYS
    - jet_pt_region_570to600_GeV_NOSYS
    - jet_pt_region_600to630_GeV_NOSYS
    - jet_pt_region_630to660_GeV_NOSYS
    - jet_pt_region_660to690_GeV_NOSYS
    - jet_pt_region_690to720_GeV_NOSYS
    - jet_pt_region_720to750_GeV_NOSYS
    - jet_pt_region_750to780_GeV_NOSYS
    - jet_pt_region_780to810_GeV_NOSYS
    - jet_pt_region_810to840_GeV_NOSYS
    - jet_pt_region_840to870_GeV_NOSYS
    - jet_pt_region_870to900_GeV_NOSYS

    - sv_invariant_mass_region_0to0point5_GeV_NOSYS
    - sv_invariant_mass_region_0point5to1_GeV_NOSYS
    - sv_invariant_mass_region_1to1point5_GeV_NOSYS
    - sv_invariant_mass_region_1point5to2_GeV_NOSYS
    - sv_invariant_mass_region_2to2point5_GeV_NOSYS
    - sv_invariant_mass_region_2point5to3_GeV_NOSYS
    - sv_invariant_mass_region_3to3point5_GeV_NOSYS
    - sv_invariant_mass_region_3point5to4_GeV_NOSYS
    - sv_invariant_mass_region_4to4point5_GeV_NOSYS
    - sv_invariant_mass_region_4point5to5_GeV_NOSYS
    - sv_invariant_mass_region_5to5point5_GeV_NOSYS
    - sv_invariant_mass_region_5point5to6_GeV_NOSYS

    # Selections for cut-flow
    - electron_selections_paper_NOSYS
    - muon_selections_paper_NOSYS
    - jet_selections_paper_NOSYS
    - dilepton_selections_paper_NOSYS

    - cutA1_el_pt_NOSYS
    - cutA2_el_eta_NOSYS
    - cutA3_el_crack_NOSYS
    - cutA4_el_tight_NOSYS
    - cutA5_mu_pt_NOSYS
    - cutA6_mu_eta_NOSYS
    - cutA7_mu_tight_NOSYS
    - cutA7_1_jet_jvt_NOSYS
    - cutA8_jet_clean_NOSYS
    - cutA9_el_clean_NOSYS
    - cutA10_mu_clean_NOSYS
    - pairing_valid_NOSYS # cutD31_pairing_valid
    - pairing_mj1_NOSYS # cutD32_mj1
    - pairing_mj2_NOSYS # cutD33_mj2
    - cutC21_exactly2leptons_NOSYS # cutC21_exactly2leptons
    - cutC22_opposite_charge_NOSYS # cutC22_opposite_charge
    - cutC23_one_el_one_mu_NOSYS # cutC23_one_el_one_mu
    - cutC24_meemu_gt50_NOSYS # cutC24_meemu_gt50
    - cutC25_exactly2jets_NOSYS # cutC25_exactly2jets


    # NEW chi2 indexed
    - new_chi_indexed_jets_NOSYS

    # NEW MISMS indexed
    - new_misms_indexed_jets_NOSYS

    # NEW MDRS indexed
    - new_mdrs_indexed_jets_NOSYS

    - weight_mc_NOSYS              # MC generator weight
    - weight_pileup_NOSYS          # pileup weight
    - weight_leptonSF_tight_NOSYS  # lepton SF
    - weight_jvt_effSF_NOSYS       # jet SF 

    - event_jet_truth_idx
    - event_jet_truth_candidates

samples:
  - name: "data"
    dsids: [0]
    campaigns: ["2022"]
    simulation_type: "data"

  - name: "ttll"
    dsids: [601230]
    campaigns: ["mc23a"]
    simulation_type: "fullsim"
